Cloud testapp
Otus-DevOps-2018-05/DmitriiKuvshinov_infra pull request #3
Opened 2018-07-04 13:04 UTC by DmitriiKuvshinov

# Выполнено ДЗ № 4

 - Написать скрипты установки ryby, mongodb и deploy приложения
 - Задание со * написать скрипт автоматического деплоя образа ВМ со стартап скриптом

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
пункт 1: запускать скрипты установок приложения и деплоя
пункт 2: запустить скрипт create_instance и через пробел указать имя инстанса

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2018-07-09 16:21 UTC, Nklya requested changes
Добрый вечер.

Дмитрий, нужно пофиксить следующие проблемы:
1. Смержить предыдущий PR 
2. Вычистить из репозитория PR_kuvshinov_template.md
3. Пофиксить конфликты (подмержить мастер в эту ветку)
4. Оформить описание PR по шаблону.

2018-07-11 06:12 UTC, DmitriiKuvshinov commented
Как именно исправить описание PR?
Все сделано по шаблону, а копипастить из лекции неохота.

2018-07-11 06:22 UTC, Nklya commented
Ты когда создаешь pull request, все автоматически подставляется из закомиченого ранее https://raw.githubusercontent.com/Otus-DevOps-2018-05/DmitriiKuvshinov_infra/master/.github/PULL_REQUEST_TEMPLATE.md

Сейчас вместо галочек сверху стоят кружочки и нет галочек снизу

2018-07-11 09:02 UTC, DmitriiKuvshinov commented
Поправил =)

2018-07-11 09:10 UTC, Nklya requested changes
Из проблем, которые нужно пофиксить:
1. Нужно вернуть запуск тестов в .travis.yml
2. Перенести файлы из прошлого ДЗ в папку VPN, а не генерировать еще одну копию

И по мелочи:
1. форматирование в ридми кривое
2. галочки в описании ДЗ нужно отмечать выполненными, а не пустыми согласно тому что выполнено

2018-07-11 09:10 UTC, Nklya commented on .travis.yml
> -- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
Почему тесты вычищены??

2018-07-11 09:10 UTC, Nklya commented on README.md
> -		HostName Internal_IP_Address
Это в ридми уже не нужно?

2018-07-11 09:10 UTC, Nklya commented on VPN/cloud-bastion.ovpn
> +#{
cloud-bastion.ovpn нужно было переместить в папку VPN, а не сделать еще одну копию в этой папке.

2018-07-11 09:10 UTC, Nklya commented on VPN/setupvpn.sh
> +#!/bin/bash
Аналогично

2018-07-11 09:10 UTC, Nklya commented on README.md
> +cloud-testapp
В ридми используется форматирование в markdown, а не текстовый файлик как здесь.
https://guides.github.com/features/mastering-markdown/

2018-07-11 09:31 UTC, DmitriiKuvshinov commented
Замечания исправил

2018-07-11 09:44 UTC, Nklya approved these changes
Да, теперь все хорошо.

Тесты падают, потому что не могут подключится к инстансу, но в принципе это не критично сейчас.

2018-07-11 09:50 UTC, Nklya commented
Ну и помеченные галочки выглядят вот так
<img width="656" alt="image" src="https://user-images.githubusercontent.com/26086394/42564252-fa10cb66-8508-11e8-9c21-fa368d61b913.png">

2018-07-11 10:12 UTC, merged