Packer base
Otus-DevOps-2018-05/DmitriiKuvshinov_infra pull request #4
Opened 2018-07-09 10:43 UTC by DmitriiKuvshinov

# Выполнено ДЗ №5

 - Основное ДЗ
 - Задание со *

## В процессе сделано:
настроен скрипт создание шаблона в GCP с параметризацией

## Как запустить проект:
 чтобы создать наполненный шаблон, необходимо запустить packer с параметрами var-file, указать какой и конфиг для щаблона
В задании со звездой необходимо запустить скрипт crate-reddit-vm.sh
Скрипт автоматически создаст ВМ из шаблона и настроит необходимое окружение

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2018-07-12 15:27 UTC, Nklya requested changes
Добрый день. 
Есть проблемы и в базовом и доп. задании.
Нужно:

- Написать хотя бы предложение в ридми на тему что сделано
- вычистить bin/packer
- cloud-bastion.ovpn и setupvpn.sh должен быть в папке VPN в корне репозитория, а не в config-scripts. Его вторая копия должна быть вычищена
- вычистить variables.json.example из корня репозитория
- В шаблонах должна быть секция variables
- Ну и packer/immutable.json в принципе нерабочий

2018-07-12 15:27 UTC, Nklya commented on README.md
>  To create new instance need: run create_instance enter_name_of_instace
Где содержимое ридми к этому ДЗ?

2018-07-12 15:27 UTC, Nklya commented on variables.json.example
> +{
Этот файл здесь зачем?
Его нужно вычистить

2018-07-12 15:27 UTC, Nklya commented on config-scripts/play-travis/test.py
> +import unittest
Это почему здесь?

2018-07-12 15:27 UTC, Nklya commented on config-scripts/cloud-bastion.ovpn
> +#{
Откуда здесь теперь два конфига???

2018-07-12 15:27 UTC, Nklya commented on packer/ubuntu16.json
> +{
Где секция variables у шаблонов?

2018-07-12 15:27 UTC, Nklya commented on packer/immutable.json
> +{
Где секция variables у шаблонов?

2018-07-12 15:27 UTC, Nklya commented on packer/scripts/deploy.sh
> +puma -d
стартовать сервисы во время билда образов нет смысла

2018-07-12 15:27 UTC, Nklya commented on packer/scripts/install_mongodb.sh
> +systemctl start mongod
стартовать сервисы во время билда образов нет смысла

2018-07-12 15:27 UTC, Nklya commented on packer/files/crate-reddit-vm.sh
> +		--metadata-from-file startup-script=startup_puma.sh
immutable.json должен генерировать готовый образ с системд юнитом для старта сервиса.
По факту он это у тебя не делает, и для этого наворочена эта дичь в скрипте с --metadata-from-file

2018-07-12 15:27 UTC, Nklya commented on packer/immutable.json
> +            "image_family": "reddit-base",
image_family для этого образа должен называться reddit-full

2018-07-12 15:27 UTC, Nklya commented on packer/files/crate-reddit-vm.sh
> +		--metadata-from-file startup-script=startup_puma.sh
Не говоря уже о то, что этот скрипт должен находится в config-scripts

2018-07-12 15:28 UTC, Nklya commented
Ну и чтобы галочки появились, туда нужно ткнуть мышкой
<img width="378" alt="image" src="https://user-images.githubusercontent.com/26086394/42643242-55a9e55e-8601-11e8-902c-67c2fc1fc981.png">

2018-07-13 09:33 UTC, DmitriiKuvshinov commented on packer/immutable.json
> +{
https://www.packer.io/docs/templates/user-variables.html
запуск производится с командой -var-file=variables.json
да, оказывается так тоже можно

2018-07-13 09:33 UTC, DmitriiKuvshinov commented on packer/scripts/deploy.sh
> +puma -d
Согласен, поправил

2018-07-13 10:37 UTC, DmitriiKuvshinov commented on packer/files/crate-reddit-vm.sh
> +		--metadata-from-file startup-script=startup_puma.sh
Добавил создание службы в immutable.json
Измнил название образа
Образ создается, службы все необходимые в нем присутствуют, включая софт
удалил лишнее из скрипта создания ВМ из образа
структуру папок постараюсь больше не нарушать

2018-07-13 10:39 UTC, DmitriiKuvshinov commented
шутка с галочками очень понравилась... всегда было интересно откуда они берутся =)

2018-07-13 17:22 UTC, Nklya requested changes
Этого конечно сложно добится, но твои коммиты не добавили порядка, если не сказать хуже.

Вот есть пример как выглядит репозиторий на этом этапе https://github.com/Otus-DevOps-2018-05/20SecondsToSun_infra/tree/packer-base
Смотришь на него и приводишь к такой же структуре.

НЕ по содержимому, а именно по СТРУКТУРЕ.

Из того, что я вижу:
1. В папке /play-travis нет того, что там должно быть
2. В папке /packer/files/ два лишних файла
3. В папке /bin лежит лишний бинарник пакера
4. В папке /config-scripts лежат копии папок VPN и play-travis

2018-07-13 17:22 UTC, Nklya commented on README.md
> +Работа с образами VM в облаке. Знакомство с Packer и экосистемой компании HashiCorp.
Ну и в ридми должно быть форматирование https://github.com/sandino/Markdown-Cheatsheet

Если это пункты, добавь в начало каждой строки звездочку, чтобы получить вот такое:

## ДЗ 5
* Работа с образами VM в облаке. Знакомство с Packer и экосистемой компании HashiCorp.
* Для создания base образа необходимо запустить билд пакера с параметром -var-file=variables.json
* Для задания со * необходимо из папки files запустить crate-reddit-vm.sh
* Немного изменил структуру папок, но заметил это уже поздно =(

2018-07-16 05:59 UTC, closed without merging