Terraform 1
Otus-DevOps-2018-05/DmitriiKuvshinov_infra pull request #8
Opened 2018-07-16 06:16 UTC by DmitriiKuvshinov

# Выполнено ДЗ 5

 - [ ] Основное ДЗ

## В процессе сделано:
Создаем VM согласно описанию

## Как запустить проект:
Запустить билд терраформа

## Как проверить работоспособность:
Проверить веб-консоль GCP

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2018-07-16 10:33 UTC, Nklya commented
Зачем закрыты старые PR и открыты новые???

2018-07-16 11:13 UTC, Nklya requested changes
Сейчас нужно:
1. Смержить предыдущий PR 
2. Подмержить в terraform-1 и terraform-2 мастер
3. Заполнить полностью имя на гитхабе

2018-07-16 12:44 UTC, DmitriiKuvshinov commented
1. Готово
2. Как я понимаю, при мердже с мастером - все подхватывается и в terraform-1 и 2 (конфликты поправил в ветке terraform-1)
3. Готово

2018-07-16 13:26 UTC, Nklya requested changes
Добрый день.

Дмитрий, условия ДЗ не выполнены:
1. Нужно параметризовать ключи пользователя (приватный и публичный)
2. Параметризовать зону
3. Вычистить из репозитория config-scripts/play-travis/test.py
4. Пофиксить нумерацию ДЗ в ридми

2018-07-16 13:26 UTC, Nklya commented on README.md
> +## ДЗ 4
Пакер - это пятое ДЗ, как я помню

2018-07-16 13:26 UTC, Nklya commented on README.md
> +## ДЗ 5
А  тераформ - шестое

2018-07-16 13:26 UTC, Nklya commented on terraform/main.tf
> +    private_key = "${file("~/.ssh/appuser")}"
Приватный ключ должен быть в переменной, а не задан здесь

2018-07-16 13:26 UTC, Nklya commented on terraform/main.tf
> +  zone         = "${var.region}"
zone - это зона, и это не то же самое, что регион

2018-07-16 13:26 UTC, Nklya commented on terraform/main.tf
> +    ssh-keys = "appuser:${file("~/.ssh/appuser.pub")}"
Здесь должна использоваться переменная по условиям ДЗ

2018-07-16 13:26 UTC, Nklya commented on packer/files/startup_puma.sh
> +sudo systemctl start puma.service
Почему здесь вдруг возвращается это?

2018-07-16 13:26 UTC, Nklya commented on packer/files/crate-reddit-vm.sh
> +		--image=reddit-base-1531118158 \
Почему здесь поменялся образ?
Почему используются полные имена вместо image-family?

2018-07-16 13:26 UTC, Nklya commented on packer/files/crate-reddit-vm.sh
> +		--metadata-from-file startup-script=startup_puma.sh
Зачем эта дичь здесь возвращается?

2018-07-16 13:26 UTC, Nklya commented on config-scripts/play-travis/test.py
> +import unittest
Это нужно вычистить

2018-07-17 06:34 UTC, DmitriiKuvshinov commented on packer/files/crate-reddit-vm.sh
> +		--metadata-from-file startup-script=startup_puma.sh
На сколько я понял доп задание, необходимо:
сделать так, чтобы служба puma запускалась при старте системы, используя initd
чем плох способ выполнения bash скрипта на стороне VM через echo запись в файл...?
Понимаю, что можно сразу скопировать готовый файл в директорию служб, но этот способ тоже имеет место быть

2018-07-17 06:37 UTC, DmitriiKuvshinov commented on packer/files/crate-reddit-vm.sh
> +		--image=reddit-base-1531118158 \
Сменил именование шаблона, согласно условию задания (там разница с фулл и бэйс)
При "запекании образа" явно указал имя шаблона, вот и использую имя

2018-07-17 10:34 UTC, Nklya commented on packer/files/crate-reddit-vm.sh
> +		--image=reddit-base-1531118158 \
Использование полных имен не особо хорошая идея, особенно в этих тестовых примерах.
Каждый новый билд нужно будет менять имя.

2018-07-17 10:35 UTC, Nklya commented on packer/files/crate-reddit-vm.sh
> +		--metadata-from-file startup-script=startup_puma.sh
Потому что immutable образ - это образ который уже готов, и ему не нужно пихать подпорки в виде startup-script чтобы оно заработало

2018-07-17 12:41 UTC, DmitriiKuvshinov commented on packer/files/crate-reddit-vm.sh
> +		--metadata-from-file startup-script=startup_puma.sh
да, Вы правы. Этот пункт описан в immutable.json 
Спасибо
Скрипт отредактировал

2018-07-17 19:06 UTC, Nklya approved these changes
Добрый вечер.

Дмитрий, условия ДЗ выполнены, теперь все выглядит ок 👍

2018-07-17 19:07 UTC, Nklya commented
Сейчас нужно смержить этот PR и подмержить мастер в следующую ветку.

2018-07-19 06:44 UTC, merged