Terraform 2
Otus-DevOps-2018-05/DmitriiKuvshinov_infra pull request #9
Opened 2018-07-16 07:00 UTC by DmitriiKuvshinov

# Выполнено ДЗ № 6

 - [ ] Основное ДЗ

## В процессе сделано:
Организации инфраструктурного кода и работа над инфраструктурой на примере Terraform

## Как запустить проект:
запустить применение terraform с указанием необходимого модуля

## Как проверить работоспособность:
Проверить в веб-консоли GCP

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2018-07-16 10:33 UTC, Nklya commented
Зачем закрыты старые PR и открыты новые???

2018-07-18 10:55 UTC, Nklya requested changes
Ревью будет выполнено после мержа предыдущего PR и подмерживания в эту ветку мастера, чтобы пофиксить конфликты

2018-07-23 08:41 UTC, Avtandilko reviewed
Дмитрий, добрый день.
В целом - все выглядит хорошо. Единственное - в файлах variables.tf.example смысла нет.

2018-07-23 08:41 UTC, Avtandilko commented on terraform/modules/db/main.tf
> +  name         = "reddit-db"
Лучше параметризовать в модуле хотя бы name.

2018-07-23 08:41 UTC, Avtandilko commented on terraform/modules/app/main.tf
> +  name         = "reddit-app"
Лучше параметризовать в модуле хотя бы name.

2018-07-23 08:48 UTC, Avtandilko approved these changes

2018-07-30 07:14 UTC, DmitriiKuvshinov commented
ветки помержил
поправил конфиги терраформа (параметризация)

2018-08-02 18:47 UTC, Avtandilko commented
Дмитрий, сейчас надо решить конфликты между этой веткой и мастером и вмерджить PR в мастер. В идеале - лучше стараться делать так, чтобы при создании пулл реквеста все конфликты уже были разрешены.

2018-08-13 13:49 UTC, DmitriiKuvshinov commented
Я б с удовольствием, но что-то пошло не так и сейчас эти конфликты не решить вообще
В консоли у себя я все порешал и ветки смержил. Запушил заново поправленную ветку terraform-2, но мердж недопустим
Можете помочь с решением конфликта?

2018-08-13 13:51 UTC, DmitriiKuvshinov commented
могу ли влить заново всю ветку (закрыть PR и удалить ветку), чтобы влить некофликтные изменения?

2018-08-13 15:32 UTC, merged